version: '3.6'
services:
  db:
    container_name: db
    image: mariadb:10.4
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bingo
      MYSQL_PASSWORD: bingo
      MYSQL_DATABASE: bingodb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bingo-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8081:80'
    restart: always
    volumes:
      - ./docker/phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on:
      - db
    networks:
      - bingo-net
  bingo-java:
    image: bingo-java:latest
    build:
      context: .
    ports:
      - '8088:8080'
    restart: always
    command: ./mvnw spring-boot:run
    depends_on:
      - db
    networks:
      - bingo-net
networks:
  bingo-net:
    name: "bingo-net"
volumes:
  db_data:
